### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by Pantyhose-X** [cuiliang/Caps2CtrlSpace#6]
你好 监听按键 是这种功能吗？

https://user-images.githubusercontent.com/42504385/127757873-c3c076d3-ce73-40b1-8f57-423459fc0c2f.MP4

监听win10输入法，TTS朗读输入
应用于语言学习。发音纠正，这样可以纠正发音和加深记忆，
母语不是英语。需要学习英语，市场非常大

**Comment by cuiliang** [comment]
不太了解。这种会受到输入错误影响。
